name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23'

    - name: Install dependencies and tools
      run: make setup

    - name: Lint
      run: make lint

    - name: Tests
      run: make test

    - name: Build
      run: make build

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: dsa:latest